### PR TITLE
feat: add find toilet near me button

### PR DESCRIPTION
**Pull request by rosejbon**
Part of #1032, adding a more visually obvious button for users on mobile to click and find loos near them. We will track it using Plauisble and compare to see if it works.

### CODE REVIEW

**Comment by marxian** [comment]
Looks good, but, it seems to me that the new button is only visible on smaller viewports.  Is that the intention?

**Comment by rosejbon** [comment]
> Looks good, but, it seems to me that the new button is only visible on smaller viewports. Is that the intention?

That is a good point Rupert. I was making an assumption about how people use the site. I will add a button onto the larger screen.

**Review by ob6160 — APPROVED** [review]
nice one

**Review by marxian — APPROVED** [review]
Nice! Good on big screens too now... And I can see the event getting sent.

**Pull request merged**
