### PR TITLE
Chloropleth stuff

### PR DESCRIPTION
**Pull request by jthistle**
WIP, description of changes to come

Tasks to run on merge:

- Drop `areas` collection on staging, run `yarn areas`. Be aware of downtime for adding new loos while this is being done.

### CODE REVIEW

**Comment by jthistle** [comment]
By number of loos:
number

By loo density:
density

**Comment by jthistle** [comment]
Probably ready for review and merging now :)

**Comment by marxian** [comment]
@jthistle Deploy is unstuck, but I get errors on the Area Map page: https://gbptm-kuzkj8l4t.vercel.app/explorer/map

The `getAreas` query is returning null...

**Comment by jthistle** [comment]
Hmmm, is the preview pointed at the staging or prod database?

**Comment by jthistle** [comment]
I'm very puzzled by this, because locally I'm running with my database set up as staging, and it's working fine.

**Comment by marxian** [comment]
If only we were all using the _same_ staging database.

My fault. I'll send you an updated .env

**Pull request merged**
