### PR TITLE
fix: only allows number input

### PR DESCRIPTION
**Pull request by roseb04**
Fixing this issue: https://github.com/neontribe/gbptm/issues/1006

### CODE REVIEW

**Comment by roseb04** [comment]
Fix doesn't currently let users know when they are incorrectly typing in a date until they've clicked submit. Even if they do put in the number format then they could put in a nonsensical time eg 25:99.

This article might hold some clues on how to make a bit of a clever fix - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#handling_browser_support

**Comment by marxian** [comment]
@gailramster when you get a moment please have a little test of @roseb04's interim solution here (it should solve the worst of the problem): https://gbptm-git-fix-opening-hours-safari.neontribe.vercel.app

**Comment by gailramster** [comment]
Looks like a good solution thought it's not letting me edit the numbers in Safari.

Screen Shot 2021-02-01 at 19 46 35

**Comment by marxian** [comment]
@gailramster We've done some investigation - it is certainly a standards-compliance issue in Safari (that's not unusual). Things are much better in current Safari editions but you seem to be pinned in an older release of OSX. Estimates suggest that 

We have options still, to fix this but it adds unwelcome complexity. @rose is thinking to add a format indicator...

**Comment by roseb04** [comment]
@gailramster I've just checked with a colleague who has the same Safari browser that you are using. It appeared that while he couldn't edit the numbers (like you could in Chrome), he could type in the box and edit that way. Are you able to type in the time?

**Comment by gailramster** [comment]
@roseb04 Hi Rose, yes now I know the 00:00 format, I can add times and they'll submit, on the toiletmap.org.uk site. I can't edit the pre-filled numbers on the interim solution.  Would suggesting the format somewhere in the question be enough?  I was probably writing 0:00, 0.00 or 0pm.

**Comment by roseb04** [comment]
@gailramster that is great news. I've updated the placeholder text so that is should be clearer that the format should be hh:mm. I will get that approved and merged in, so we can close this issue.

**Review by marxian — APPROVED** [review]

**Pull request merged**
